1. Write a Python Program to Add Two Matrices?

In [42]:
from numpy import matrix
def add_matrices():
    m1=list(map(int,input("Please enter numbers for 1st matrix: ").strip()))
    m2=list(map(int,input("Please enter numbers for 2nd matrix: ").strip()))
    print(m1,m2)
    new_m1=matrix(m1)
    new_m2=matrix(m2)
    l=new_m1 + new_m2 
    return  l

In [43]:
add_matrices()

Please enter numbers for 1st matrix: 154
Please enter numbers for 2nd matrix: 254
[1, 5, 4] [2, 5, 4]


matrix([[ 3, 10,  8]])

2. Write a Python Program to Multiply Two Matrices?

In [5]:
from numpy import *
'''
Matrix multiplication is some special kind of ultipication where we need to take care few things for multipication.
for ex. if there are two matrices with mxn and jxk dimentions respectively than their multiplication will only be possible
if m=j. the resultant matrix would be mxk.
'''
def mul_matrices():
    
    try:        
        m1=list(map(int,input("Please enter numbers for 1st matrix: ").strip()))
        m2=list(map(int,input("Please enter numbers for 2nt matrix: ").strip()))
        R1=int(input("please enter the number in which you want the row of 1st matrix: "))
        C1=int(input("please enter the number in which you want the coloumn of 1nt matrix: "))
        R2=int(input("please enter the number in which you want the row of 2nd matrix: "))
        C2=int(input("please enter the number in which you want the coloumn of 2nd matrix: "))
        k=array(m1).reshape(R1,C1)    
        l=array(m2).reshape(R2,C2)
        return matrix(k)*matrix(l)
    except Exception as e:
        print(e)
        print("this multiplication is not possible please try again")
        mul_matrices()
    
    
    

In [4]:
mul_matrices()

Please enter numbers for 1st matrix: 245125415321
Please enter numbers for 2nt matrix: 548456124578
please enter the number in which you want the row of 1st matrix: 3
please enter the number in which you want the coloumn of 1nt matrix: 4
please enter the number in which you want the row of 2nd matrix: 4
please enter the number in which you want the coloumn of 2nd matrix: 3


matrix([[36, 45, 68],
        [39, 48, 70],
        [44, 46, 74]])

3. Write a Python Program to Transpose a Matrix?

In [10]:
def transpose_matrix():
    m1=list(map(int,input("Please enter numbers which you want in matrix: ").strip()))
    R1=int(input("please enter the number row you want in matrix: "))
    C1=int(input("please enter the number column you want in matrix: "))
    created_matrix=matrix(array(m1).reshape(R1,C1))
    return created_matrix.transpose()
    
    

In [11]:
transpose_matrix()

Please enter numbers which you want in matrix: 123456789
please enter the number row you want in matrix: 3
please enter the number column you want in matrix: 3


matrix([[1, 4, 7],
        [2, 5, 8],
        [3, 6, 9]])

4. Write a Python Program to Sort Words in Alphabetic Order?

In [18]:
def sortingWords(number_of_words):
    user_input=[input(f"Please input the {i} word which you want to sort ") for i in range(1,number_of_words+1)]
    return sorted(user_input)

In [20]:
sortingWords(3)


Please input the 1 word which you want to sort Somesh
Please input the 2 word which you want to sort Raj
Please input the 3 word which you want to sort Vyom


['Raj', 'Somesh', 'Vyom']

5. Write a Python Program to Remove Punctuation From a String?

In [37]:
import string
userInput=input("Please enter your string here: ")
for i in userInput:
    if i in string.punctuation:        
        userInput=userInput.replace(i,'')        
        
print('Final Output is: ',userInput)

Please enter your string here:  Hey! Ya you, Comon: $20 is there
Final Output is:   Hey Ya you Comon 20 is there


In [25]:
string.punctuation

'!"#$%&\'()*+,-./:;<=>?@[\\]^_`{|}~'